import { defineNuxtModule } from 'nuxt/kit'
import type { ModuleDependencies, NuxtModule } from 'nuxt/schema'
import { resolveSpecOptions } from '../config/utils/options.mjs'
import type { NuxtSpecOptions } from '../config/utils/options.mjs'

// registers typed `spec` key for nuxt.config.ts and applies its Nuxt-related options
// options related to Vitest are resolved in `loadVitestConfig` (config/index.mjs)
// (explicit types break circular reference with module types generated by Nuxt)
const specOptionsModule: NuxtModule<NuxtSpecOptions> = defineNuxtModule<NuxtSpecOptions>({
  meta: {
    name: 'nuxt-spec',
    configKey: 'spec',
    // used as `@see` link in generated types (fallback would be a broken npm URL)
    docs: 'https://nuxt-spec.netlify.app/2-1-configuration.html#nuxt-spec-options',
  },
  moduleDependencies: (nuxt): ModuleDependencies => {
    // `spec` is typed only after Nuxt generates module types
    const { spec } = nuxt.options as unknown as { spec?: NuxtSpecOptions | false }
    return resolveSpecOptions(spec).hints ? { '@nuxt/hints': {} } : {}
  },
})

export default specOptionsModule
