# settings for Nuxt & pnpm

packages:
  - .
  - docs

# moved from .npmrc
# https://pnpm.io/settings/node-modules#shamefullyhoist
shamefullyHoist: true

# moved from package.json
# https://pnpm.io/settings/build#allowbuilds
allowBuilds:
  # provides fallback repair of platform-specific Rust native engine
  'unrs-resolver': true
  # allows node-gyp build of associated native binaries from local sources
  # disabled because it would require an explicit opt-in
  '@parcel/watcher': false
  # optimization for CLI usage of 'esbuild'
  # disabled because its runtime resolves native binaries itself
  'esbuild': false

overrides:
  # use Vite 8
  'vite': '^8.1.0'
  # CVE-2026-69152
  'brace-expansion@2': '^2.1.4'
  'brace-expansion@5': '^5.0.9'
  # CVE-2026-59869
  'js-yaml': '^4.3.1'
  # CVE-2026-69153
  'postcss': '^8.5.26'

# https://pnpm.io/settings/dependency-resolution#minimumreleaseageexclude
minimumReleaseAgeExclude:
  # build 2026-08-08 @ 16:10 CEST
  - happy-dom@20.11.2
