# settings for Nuxt & pnpm

# migrated from .npmrc
# https://pnpm.io/settings#shamefullyhoist
shamefullyHoist: true

# migrated from package.json
# https://pnpm.io/settings#onlybuiltdependencies
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true

# use Vite 8
overrides:
  'vite': '^8.0.16'

minimumReleaseAgeExclude:
  # build @ 2026-06-02 13:45 GMT+2
  - elrh-cosca@0.3.6
